### ISSUE TITLE
Choose a TUI library

### ISSUE THREAD

**Issue by Vulcalien** [Vulcalien/unict-qd-sudoku#1]
[Urwid](https://urwid.org/) is a Python TUI library. It seems appropriate for this project.

**Comment by Henryskio** [comment]
Hi, I did a little bit of "research "and I think I would prefer something a little bit [more modern](https://github.com/Textualize/textual) than Urwid.
Also Urwid doesn't support Windows.

**Comment by Vulcalien** [comment]
Textual looks good. We now need a basic UI design and then we can start writing it using Textual.
